### YamlMime:PowershellCmdlet
summary: |-
  Adds an owner to an application.
module: AzureAD
notes: ""
syntaxes:
- >-
  Add-AzureADApplicationOwner -ObjectId <String> -RefObjectId <String> [-InformationAction <ActionPreference>]

   [-InformationVariable <String>] [<CommonParameters>]
examples:
- title: 'Example 1: Add a user as an owner to an application'
  code: |-
    PS C:\> $ApplicationId = (Get-AzureADApplication -Top 1).ObjectId
    PS C:\> $UserObjectId = (Get-AzureADUser -Top 1).ObjectId
    PS C:\> Add-AzureADApplicationOwner -ObjectId $ApplicationId -RefObjectId $UserObjectId
  description: |-
    This command adds an owner to an application.
  summary: ""
parameters:
- type: <xref href="ActionPreference" data-throw-if-not-resolved="False" />
  name: InformationAction
  description: |+
    Specifies how this cmdlet responds to an information event.
    The acceptable values for this parameter are: * Continue

    * Ignore
    * Inquire
    * SilentlyContinue
    * Stop
    * Suspend

  defaultValue: None
  position: Named
  aliases: infa
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: InformationVariable
  description: |+
    Specifies a variable in which to store an information event message.

  defaultValue: None
  position: Named
  aliases: iv
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ObjectId
  isRequired: true
  description: |+
    Specifies the ID of an application in Microsoft Entra ID.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: RefObjectId
  isRequired: true
  description: |+
    Specifies the ID of the Microsoft Entra ID object to assign as owner/manager/member.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: AzureAD.Add-AzureADApplicationOwner
name: Add-AzureADApplicationOwner
description: |-
  The Add-AzureADApplicationOwner cmdlet adds an owner to a Microsoft Entra ID application.
metadata:
  external help file: Microsoft.Open.AzureAD16.Graph.PowerShell.dll-Help.xml
  Module Name: AzureAD
  online version: ""
  schema: 2.0.0
