### YamlMime:PowershellCmdlet
summary: |-
  Adds a new key to an application.
module: AzureAD
notes: ""
inputs:
- name: <xref href="string" data-throw-if-not-resolved="False" />
  description: ""
- name: <xref href="Microsoft.Open.MSGraph.Model.KeyCredential" data-throw-if-not-resolved="False" />
  description: ""
- name: <xref href="Microsoft.Open.MSGraph.Model.PasswordCredential" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Microsoft.Open.MSGraph.Model.KeyCredential" data-throw-if-not-resolved="False" />
  description: ""
syntaxes:
- >-
  New-AzureADMSApplicationKey -ObjectId <String> -KeyCredential <KeyCredential>

   [-PasswordCredential <PasswordCredential>] -Proof <String> [<CommonParameters>]
examples:
- title: 'Example 1: Add a key credential to an application'
  code: |-
    PS C:\>New-AzureADMSApplicationKey -ObjectId aaaaaaaa-0000-1111-2222-bbbbbbbbbbbb -KeyCredential @{ key=[System.Convert]::FromBase64String("{base64cert}") } -PasswordCredential @{ displayname = "mypassword" } -Proof "{token}"
  description: |-
    This command adds a key credential the specified application.
  summary: ""
parameters:
- type: <xref href="KeyCredential" data-throw-if-not-resolved="False" />
  name: KeyCredential
  isRequired: true
  description: |+
    The application key credential to add.

    NOTES: keyId value should be null.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ObjectId
  isRequired: true
  description: |+
    The unique identifier of the object specific Azure Active Directory object

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="PasswordCredential" data-throw-if-not-resolved="False" />
  name: PasswordCredential
  description: |+
    The application password credential to add.

    NOTES: keyId value should be null.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Proof
  isRequired: true
  description: |+
    A signed JWT token used as a proof of possession of the existing keys

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: AzureAD.New-AzureADMSApplicationKey
name: New-AzureADMSApplicationKey
description: |-
  Adds a new key to an application.
metadata:
  external help file: Microsoft.Open.MS.GraphV10.PowerShell.dll-Help.xml
  Module Name: AzureAD
  online version: ""
  schema: 2.0.0
