### YamlMime:PowershellCmdlet
summary: |-
  Removes a password credential from an application.
module: AzureAD
notes: ""
syntaxes:
- >-
  Remove-AzureADApplicationPasswordCredential -ObjectId <String> -KeyId <String>

   [-InformationAction <ActionPreference>] [-InformationVariable <String>] [<CommonParameters>]
examples:
- title: 'Example 1: Remove an application password credential'
  code: |-
    PS C:\> $AppID = (Get-AzureADApplication -Top 1).objectId
    PS C:\> $KeyIDs = Get-AzureADApplicationPasswordCredential -ObjectId $AppId
    PS C:\> Remove-AzureADApplicationPasswordCredential -ObjectId $AppId -KeyId $KeyIds[0].KeyId
  description: |-
    The first command gets the ID of an application by using the Get-AzureADApplication (./Get-AzureADApplication.md)cmdlet, and then stores it in the $AppID variable.

    The second command gets the password credential for the application identified by $AppID by using the Get-AzureADApplicationPasswordCredential (./ Get-AzureADApplicationPasswordCredential.md)cmdlet. 
    The command stores it in the $KeyId variable.

    The final command removes the application password credential for the application identified by $AppID.
  summary: ""
parameters:
- type: <xref href="ActionPreference" data-throw-if-not-resolved="False" />
  name: InformationAction
  description: |+
    Specifies how this cmdlet responds to an information event.

    The acceptable values for this parameter are:

    - Continue
    - Ignore
    - Inquire
    - SilentlyContinue
    - Stop
    - Suspend

  defaultValue: None
  position: Named
  aliases: infa
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: InformationVariable
  description: |+
    Specifies an information variable.

  defaultValue: None
  position: Named
  aliases: iv
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: KeyId
  isRequired: true
  description: |+
    @{Text=}

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ObjectId
  isRequired: true
  description: |+
    Specifies the ID of the application in Azure AD.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: AzureAD.Remove-AzureADApplicationPasswordCredential
name: Remove-AzureADApplicationPasswordCredential
description: |-
  The Remove-AzureADApplicationPasswordCredential cmdlet removes a password credential from an application in Azure Active Directory (AD).
metadata:
  external help file: Microsoft.Open.AzureAD16.Graph.PowerShell.Custom.dll-Help.xml
  Module Name: AzureAD
  online version: ""
  schema: 2.0.0
