### YamlMime:PowershellCmdlet
summary: |-
  The Remove-AzureADApplicationProxyConnectorGroup cmdlet deletes an Application Proxy Connector group.
module: AzureAD
notes: ""
inputs:
- name: <xref href="System.String" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="System.Object" data-throw-if-not-resolved="False" />
  description: ""
syntaxes:
- Remove-AzureADApplicationProxyConnectorGroup -Id <String> [<CommonParameters>]
examples:
- title: Example 1
  code: |-
    PS C:\> Remove-AzureADApplicationProxyConnectorGroup -Id 59462d3c-a1bc-40a0-9bed-be799357ebce
  description: |-
    Example 1: Remove a specific Connector Group
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Id
  isRequired: true
  description: |+
    The Id of the Connector group to delete.
    You can find this value by running the Get-AzureADApplicationProxyConnectorGroup command.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: AzureAD.Remove-AzureADApplicationProxyConnectorGroup
name: Remove-AzureADApplicationProxyConnectorGroup
description: |-
  The Remove-AzureADApplicationProxyConnectorGroup cmdlet deletes an Application Proxy Connector Group.
  It can only be used on an empty connector group, with no connectors assigned.
metadata:
  external help file: Microsoft.Open.MS.GraphV10.PowerShell.dll-Help.xml
  Module Name: AzureAD
  online version: ""
  schema: 2.0.0
