### YamlMime:PowershellCmdlet
summary: |-
  Remove a password from an application.
module: AzureAD
notes: ""
inputs:
- name: <xref href="string" data-throw-if-not-resolved="False" />
  description: ""
syntaxes:
- Remove-AzureADMSApplicationPassword -ObjectId <String> [-KeyId <String>] [<CommonParameters>]
examples:
- title: 'Example 1: Removes a password from an application'
  code: |-
    PS C:\>Remove-AzureADMSApplicationPassWord -ObjectId aaaaaaaa-0000-1111-2222-bbbbbbbbbbbb -KeyId aaaaaaaa-0b0b-1c1c-2d2d-333333333333
  description: |-
    This command remove the specified password from the specified application.
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: KeyId
  description: |+
    The unique identifier for the key.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ObjectId
  isRequired: true
  description: |+
    The unique identifier of the object specific Azure Active Directory object

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: AzureAD.Remove-AzureADMSApplicationPassword
name: Remove-AzureADMSApplicationPassword
description: |-
  Remove a password from an application.
metadata:
  external help file: Microsoft.Open.MS.GraphV10.PowerShell.dll-Help.xml
  Module Name: AzureAD
  online version: ""
  schema: 2.0.0
