### YamlMime:PowershellCmdlet
summary: |-
  The Set-AzureADApplicationProxyConnector cmdlet allows reassignment of the connector to another connector group.
module: AzureAD
notes: ""
syntaxes:
- Set-AzureADApplicationProxyConnector -Id <String> -ConnectorGroupId <String> [<CommonParameters>]
examples:
- title: Example 1
  code: |-
    PS C:\> Set-AzureADApplicationProxyConnector -Id 834c5dd6-f2e8-47ae-973a-9fc769289b3d -ConnectorGroupId a39b9095-8dc8-4d3a-86c3-e7b5c3f0fb84
  description: |-
    Example 1: Move a Connector to a different Connector Group
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ConnectorGroupId
  isRequired: true
  description: |+
    The unique identifer of the target application proxy connector group in Azure Active Directory.
    You can find this value using the Get-AzureAdApplicationProxyConnectorGroup command.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Id
  isRequired: true
  description: |+
    The Id of the Connector being moved.
    You can find this value using the Get-AzureADApplicationProxyConnector command.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: AzureAD.Set-AzureADApplicationProxyConnector
name: Set-AzureADApplicationProxyConnector
description: |-
  The Set-AzureADApplicationProxyConnector cmdlet allows reassignment of the connector to another connector group.
metadata:
  external help file: Microsoft.Open.MS.GraphV10.PowerShell.Custom.dll-Help.xml
  Module Name: AzureAD
  online version: ""
  schema: 2.0.0
