### YamlMime:PowershellCmdlet
summary: |-
  Sets the logo for an Application
module: AzureAD
notes: ""
inputs:
- name: <xref href="System.String" data-throw-if-not-resolved="False" />
  description: |-
    System.IO.Stream System.Byte\[\]
outputs:
- name: <xref href="System.Object" data-throw-if-not-resolved="False" />
  description: ""
syntaxes:
- Set-AzureADApplicationLogo [-ObjectId <String>] -FilePath <String> [<CommonParameters>]
- Set-AzureADApplicationLogo [-ObjectId <String>] -FileStream <Stream> [<CommonParameters>]
- Set-AzureADApplicationLogo [-ObjectId <String>] -ImageByteArray <Byte[]> [<CommonParameters>]
examples:
- title: Example 1
  code: |-
    PS C:\WINDOWS\system32> Set-AzureADApplicationLogo -ObjectId aaaaaaaa-0000-1111-2222-bbbbbbbbbbbb -FilePath D:\applogo.jpg
  description: |-
    This cmdlet sets the application logo for the application specified by the the ObjectID parameter to the image specified with the FIlepath parameter
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: FilePath
  isRequired: true
  description: |+
    The file path of the file that is to be uploaded as the application logo

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Stream" data-throw-if-not-resolved="False" />
  name: FileStream
  isRequired: true
  description: |+
    A fileStream that is to be used as the application logo

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Byte" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: ImageByteArray
  isRequired: true
  description: |+
    And ImageByteArray that is to be used as the application logo

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ObjectId
  description: |+
    The ObjectID of the Application for which the logo is set

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: AzureAD.Set-AzureADApplicationLogo
name: Set-AzureADApplicationLogo
description: |-
  This cmdlet is used to set the logo for an application
metadata:
  external help file: Microsoft.Open.AzureAD16.Graph.PowerShell.Custom.dll-Help.xml
  Module Name: AzureAD
  online version: ""
  schema: 2.0.0
