### YamlMime:PowershellCmdlet
summary: |-
  The Set-AzureADApplicationProxyApplicationConnectorGroup cmdlet assigns the given connector group to a specified application.
module: AzureAD
notes: ""
inputs:
- name: <xref href="System.String" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="System.Object" data-throw-if-not-resolved="False" />
  description: ""
syntaxes:
- >-
  Set-AzureADApplicationProxyApplicationConnectorGroup -ObjectId <String> -ConnectorGroupId <String>

   [<CommonParameters>]
examples:
- title: Example 1
  code: |-
    PS C:\> Set-AzureADApplicationProxyApplicationConnectorGroup -ObjectId aaaaaaaa-0000-1111-2222-bbbbbbbbbbbb -ConnectorGroupId bbbbbbbb-1111-2222-3333-cccccccccccc
  description: |-
    Example 1: Set a new Connector Group for a specific application
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ConnectorGroupId
  isRequired: true
  description: |+
    The Id of the Connector group that should be assigned to the application.
    You can find this by using the Get-AzureADApplicationProxyConnectorGroup command.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ObjectId
  isRequired: true
  description: |+
    The unique application Id for the application the Connector group will be assigned to.
    This can be found using the Get-AzureADApplication command.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: AzureAD.Set-AzureADApplicationProxyApplicationConnectorGroup
name: Set-AzureADApplicationProxyApplicationConnectorGroup
description: |-
  The Set-AzureADApplicationProxyApplicationConnectorGroup cmdlet sets the connector group assigned for the specified application.
  The application must be configured for Application Proxy in Azure Active Directory (AD).
metadata:
  external help file: Microsoft.Open.MS.GraphV10.PowerShell.Custom.dll-Help.xml
  Module Name: AzureAD
  online version: ""
  schema: 2.0.0
