### YamlMime:PowershellCmdlet
summary: |-
  The Set-AzureADApplicationProxyApplication allows you to modify and set configurations for an application in Azure Active Directory configured to use ApplicationProxy.
module: AzureAD
notes: ""
syntaxes:
- >-
  Set-AzureADApplicationProxyApplication -ObjectId <String> [-ExternalUrl <String>] [-InternalUrl <String>]

   [-ExternalAuthenticationType <ExternalAuthenticationTypeEnum>] [-IsTranslateHostHeaderEnabled <Boolean>]

   [-IsHttpOnlyCookieEnabled <Boolean>] [-IsSecureCookieEnabled <Boolean>] [-IsPersistentCookieEnabled <Boolean>]

   [-IsTranslateLinksInBodyEnabled <Boolean>] [-ApplicationServerTimeout <ApplicationServerTimeoutEnum>]

   [-ConnectorGroupId <String>] [<CommonParameters>]
examples:
- title: Example 1
  code: |-
    PS C:\> Set-AzureADApplicationProxyApplication -ObjectId aaaaaaaa-0000-1111-2222-bbbbbbbbbbbb -IsTranslateLinksInBodyEnabled $true


    ExternalAuthenticationType               : AadPreAuthentication
    ApplicationServerTimeout                 : Default
    ExternalUrl                              : https://finance-awcycles.msappproxy.net/
    InternalUrl                              : http://finance/
    IsTranslateHostHeaderEnabled             : True
    IsTranslateLinksInBodyEnabled            : True
    IsOnPremPublishingEnabled                : True
    VerifiedCustomDomainCertificatesMetadata : 
    VerifiedCustomDomainKeyCredential        : 
    VerifiedCustomDomainPasswordCredential   : 
    SingleSignOnSettings                     :
  description: |-
    Example 1: Add the link translation feature to an application
  summary: ""
parameters:
- type: <xref href="ApplicationServerTimeoutEnum" data-throw-if-not-resolved="False" />
  name: ApplicationServerTimeout
  description: |+
    Specifies the backend server timeout type.
    Set this value to Long only if your application is slow to authenticate and connect.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ConnectorGroupId
  description: |+
    Provide the Id of the Connector group you would like assigned to this application.
    You can find this value by using the Get-AzureADApplicationProxyConnectorGroup command.
    Connectors process the remote access to your application, and connector groups help you organize connectors and apps by region, network, or purpose.
    If you don't have any connector groups created yet, your app is assigned to Default.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="ExternalAuthenticationTypeEnum" data-throw-if-not-resolved="False" />
  name: ExternalAuthenticationType
  description: |+
    How Application Proxy verifies users before giving them access to your application. 
    AadPreAuth: Application Proxy redirects users to sign in with Azure AD, which authenticates their permissions for the directory and application.
    We recommend keeping this option as the default, so that you can take advantage of Azure AD security features like conditional access and Multi-Factor Authentication.
    Passthru: Users don't have to authenticate against Azure Active Directory to access the application.
    You can still set up authentication requirements on the backend.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ExternalUrl
  description: |+
    The address your users will go to in order to access the app from outside your network.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: InternalUrl
  description: |+
    The URL that you use to access the application from inside your private network.
    You can provide a specific path on the backend server to publish, while the rest of the server is unpublished.
    In this way, you can publish different sites on the same server as different apps, and give each one its own name and access rules.
    If you publish a path, make sure that it includes all the necessary images, scripts, and style sheets for your application.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: IsHttpOnlyCookieEnabled
  description: |+
    {{ Fill IsHttpOnlyCookieEnabled Description }}

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: IsPersistentCookieEnabled
  description: |+
    {{ Fill IsPersistentCookieEnabled Description }}

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: IsSecureCookieEnabled
  description: |+
    {{ Fill IsSecureCookieEnabled Description }}

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: IsTranslateHostHeaderEnabled
  description: |+
    If set to true, translates urls in headers.
    Keep this value true unless your application required the original host header in the authentication request.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: IsTranslateLinksInBodyEnabled
  description: |+
    If set to true, translates urls in body.
    Keep this value as No unless you have hardcoded HTML links to other on-premises applications, and don't use custom domains.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ObjectId
  isRequired: true
  description: |+
    Specifies a unique application ID of an application in Azure Active Directory.
    This can be found using the Get-AzureADApplication command.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: AzureAD.Set-AzureADApplicationProxyApplication
name: Set-AzureADApplicationProxyApplication
description: |-
  The Set-AzureADApplicationProxyApplication allows you to modify and set additional settings for an application in Azure Active Directory configured to use ApplicationProxy.
metadata:
  external help file: Microsoft.Open.MS.GraphV10.PowerShell.Custom.dll-Help.xml
  Module Name: AzureAD
  online version: ""
  schema: 2.0.0
