### YamlMime:PowershellCmdlet
summary: |-
  The Set-AzureADApplicationProxyApplicationCustomDomainCertificate cmdlet assigns a certificate to an application configured for Application Proxy in Azure Active Directory (AD).
  This will upload the certificate and allow the application to use Custom Domains.
module: AzureAD
notes: ""
inputs:
- name: <xref href="System.String" data-throw-if-not-resolved="False" />
  description: |-
    System.Security.SecureString
outputs:
- name: <xref href="System.Object" data-throw-if-not-resolved="False" />
  description: ""
syntaxes:
- >-
  Set-AzureADApplicationProxyApplicationCustomDomainCertificate -ObjectId <String> -PfxFilePath <String>

   -Password <SecureString> [<CommonParameters>]
examples:
- title: Example 1
  code: |-
    PS C:\> $securePassword = Read-Host -AsSecureString
    PS C:\> Set-AzureADApplicationProxyApplicationCustomDomainCertificate -ObjectId aaaaaaaa-0000-1111-2222-bbbbbbbbbbbb -PfxFilePath "C:\Temp\Certificates\cert.pfx" -Password $securePassword
  description: |-
    Example 1: Assign a certificate to an application configured for Application Proxy
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ObjectId
  isRequired: true
  description: |+
    The unique application Id for the application the certificate should be uploaded to.
    This can be found using the Get-AzureADApplication command.
    You can also find this in the Azure Portal by navigating to AAD, Enterprise Applications, All Applications, Select your application, go to the properties tab, and use the ObjectId on that page.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SecureString" data-throw-if-not-resolved="False" />
  name: Password
  isRequired: true
  description: |+
    A secure string containing the password for the pfx certificate

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: PfxFilePath
  isRequired: true
  description: |+
    The file path for the pfx certificate for the custom domain

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: AzureAD.Set-AzureADApplicationProxyApplicationCustomDomainCertificate
name: Set-AzureADApplicationProxyApplicationCustomDomainCertificate
description: |-
  The Set-AzureADApplicationProxyApplicationCustomDomainCertificate cmdlet assigns a certificate to an application configured for Application Proxy in Azure Active Directory (AD).
  This will upload the certificate and allow the application to use Custom Domains.
  If you have one certificate that includes many of your applications, you only need to upload it with one application and it will also be assigned to the other relevant applications.
metadata:
  external help file: Microsoft.Open.MS.GraphV10.PowerShell.Custom.dll-Help.xml
  Module Name: AzureAD
  online version: ""
  schema: 2.0.0
