### YamlMime:PowershellCmdlet
summary: |-
  Gets key settings for a federated domain.
module: MSOnline
notes: ""
outputs:
- name: <xref href="Microsoft.Online.Administration.DomainFederationSettings" data-throw-if-not-resolved="False" />
  description: |-
    This cmdlet returns the following settings:

    * ActiveLogOnUri
    * FederationBrandName
    * IssuerUri
    * LogOffUri
    * MetadataExchangeUri
    * NextSigningCertificate
    * PassiveLogOnUri
    * SigningCertificate
links:
- text: Get-MsolFederationProperty
  href: ./Get-MsolFederationProperty.yml
- text: Set-MsolDomainFederationSettings
  href: ./Set-MsolDomainFederationSettings.yml
syntaxes:
- Get-MsolDomainFederationSettings -DomainName <String> [-TenantId <Guid>] [<CommonParameters>]
examples:
- title: 'Example 1: Return federation settings'
  code: |-
    PS C:\> Get-MsolDomainFederationSettings -DomainName "contoso.com"
  description: |-
    This command returns the federation settings for contoso.com.
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: DomainName
  isRequired: true
  description: |+
    Specifies the fully qualified domain name to retrieve.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Guid" data-throw-if-not-resolved="False" />
  name: TenantId
  description: |+
    Specifies the unique ID of the tenant on which to perform the operation.
    The default value is the tenant of the current user.
    This parameter applies only to partner users.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: MSOnline.Get-MsolDomainFederationSettings
name: Get-MsolDomainFederationSettings
description: |-
  The **Get-MsolDomainFederationSettings** cmdlet gets key settings for a federated domain from Azure Active Directory.
  Use the [Get-MsolFederationProperty](./Get-MsolFederationProperty.yml) cmdlet to get settings for both Azure Active Directory and the Active Directory Federation Services server.
metadata:
  external help file: Microsoft.Online.Administration.Automation.PSModule.dll-Help.xml
  online version: ""
  schema: 2.0.0
  ms.assetid: 14330E4B-4E9C-4A11-8A11-47222B149052
  ms.reviewer: stevemutungi
  ms.custom: iamfeature=PowerShell
