### YamlMime:PowershellCmdlet
summary: |-
  Removes a password for an application.
module: MSOnline
notes: ""
syntaxes:
- >-
  Remove-MsolApplicationPassword -UserPrincipalName <String> -PasswordId <String> [-TenantId <Guid>]

   [<CommonParameters>]
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: PasswordId
  isRequired: true
  description: |+
    Specifies the ID of the password to remove.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Guid" data-throw-if-not-resolved="False" />
  name: TenantId
  description: |+
    Specifies the unique ID of the tenant on which to perform the operation.
    The default value is the tenant of the current user.
    This parameter applies only to partner users.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: UserPrincipalName
  isRequired: true
  description: |+
    Specifies the user principal name for which to remove a password.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: MSOnline.Remove-MsolApplicationPassword
name: Remove-MsolApplicationPassword
description: |-
  The **Remove-MsolApplicationPassword** cmdlet removes a password for an application.
metadata:
  external help file: Microsoft.Online.Administration.Automation.PSModule.dll-Help.xml
  online version: ""
  schema: 2.0.0
  ms.assetid: 13ECD260-8B3D-4D47-9109-86DDFC235C92
  ms.reviewer: stevemutungi
  ms.custom: iamfeature=PowerShell
