### YamlMime:PowershellCmdlet
summary: |-
  **The Add-AzureADApplicationPolicy cmdlet is not available at this time**.
module: AzureADPreview
notes: ""
links:
- text: Get-AzureADApplicationPolicy
  href: ./Get-AzureADApplicationPolicy.yml
- text: Remove-AzureADApplicationPolicy
  href: ./Remove-AzureADApplicationPolicy.yml
syntaxes:
- >-
  Add-AzureADApplicationPolicy -Id <String> -RefObjectId <String> [-InformationAction <ActionPreference>]

   [-InformationVariable <String>] [<CommonParameters>]
examples:
- title: 'Example 1: Add an application policy'
  code: |-
    PS C:\>Add-AzureADApplicationPolicy -ObjectId <object id of application> -RefObjectId <object id of policy>
  description: |-
    This command adds an application policy.
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Id
  isRequired: true
  description: |+
    The ID of the application for which you need to set the policy

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="ActionPreference" data-throw-if-not-resolved="False" />
  name: InformationAction
  description: |+
    Specifies how this cmdlet responds to an information event.
    The acceptable values for this parameter are:
    * Continue
    * Ignore
    * Inquire
    * SilentlyContinue
    * Stop
    * Suspend

  defaultValue: None
  position: Named
  aliases: infa
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: InformationVariable
  description: |+
    Specifies a variable in which to store an information event message.


  defaultValue: None
  position: Named
  aliases: iv
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: RefObjectId
  isRequired: true
  description: |+
    Specifies the ID of the policy.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: AzureADPreview.Add-AzureADApplicationPolicy
name: Add-AzureADApplicationPolicy
description: |-
  The **Add-AzureADApplicationPolicy** cmdlet adds an Azure Active Directory application policy.
metadata:
  external help file: Microsoft.Open.MS.GraphBeta.PowerShell.dll-Help.xml
  Module Name: AzureADPreview
  ms.assetid: 1E76B8D2-A7DF-49EE-8E22-6BFEE24A8B7F
  ms.custom: iamfeature=PowerShell
  ms.reviewer: stevemutungi
  online version: ""
  schema: 2.0.0
