### YamlMime:PowershellCmdlet
summary: |-
  Adds a predefined value for a custom security attribute definition.
module: AzureADPreview
notes: ""
inputs:
- name: <xref href="System.String" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="System.Object" data-throw-if-not-resolved="False" />
  description: ""
syntaxes:
- >-
  Add-AzureADMScustomSecurityAttributeDefinitionAllowedValues -CustomSecurityAttributeDefinitionId <String>

   -Id <String> -IsActive <Boolean> [<CommonParameters>]
examples:
- title: Example
  code: |-
    Add-AzureADMScustomSecurityAttributeDefinitionAllowedValues -CustomSecurityAttributeDefinitionId Engineering_Project -Id "Alpine" -IsActive $true
  description: |-
    Add a predefined value:

    - Attribute set: `Engineering`
    - Attribute: `Project`
    - Predefined value: `Alpine`
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: CustomSecurityAttributeDefinitionId
  isRequired: true
  description: |+
    The unique identifier for a custom security attribute definition in Azure AD.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Id
  isRequired: true
  description: |+
    The unique identifier of an object in Azure AD.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: IsActive
  isRequired: true
  description: |+
    Indicates whether the predefined value is active or deactivated. If set to false, this predefined value cannot be assigned to any additional supported directory objects.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: AzureADPreview.Add-AzureADMScustomSecurityAttributeDefinitionAllowedValues
name: Add-AzureADMScustomSecurityAttributeDefinitionAllowedValues
description: |-
  Adds a predefined value for a Azure Active Directory (Azure AD) custom security attribute definition.
metadata:
  external help file: Microsoft.Open.MS.GraphBeta.PowerShell.dll-Help.xml
  Module Name: AzureADPreview
  online version: ""
  schema: 2.0.0
