### YamlMime:PowershellCmdlet
summary: |-
  Gets an application.
module: AzureADPreview
notes: ""
links:
- text: New-AzureADApplication
  href: ./New-AzureADApplication.yml
- text: Remove-AzureADApplication
  href: ./Remove-AzureADApplication.yml
- text: Set-AzureADApplication
  href: ./Set-AzureADApplication.yml
syntaxes:
- Get-AzureADApplication [-All <Boolean>] [-Top <Int32>] [-Filter <String>] [<CommonParameters>]
- Get-AzureADApplication [-SearchString <String>] [-All <Boolean>] [<CommonParameters>]
- Get-AzureADApplication -ObjectId <String> [-All <Boolean>] [<CommonParameters>]
examples:
- title: 'Example 1: Get an application by display name'
  code: |-
    PS C:\>Get-AzureADApplication -Filter "DisplayName eq 'TestName'"

    ObjectId                             AppId                                DisplayName
    --------                             -----                                -----------
    3ddd22e7-a150-4bb3-b100-e410dea1cb84 36ee4c6c-0812-40a2-b820-b22ebd02bce3 TestName
  description: |-
    This command gets an application by its display name.
  summary: ""
- title: 'Example 2: Get an application by ID'
  code: |-
    PS C:\>Get-AzureADApplication -Filter "AppId eq '00001111-aaaa-2222-bbbb-3333cccc4444'"
  description: |-
    This command gets an application by its ID.

    Output:

        ObjectId                             AppId                                DisplayName
        --------                             -----                                -----------  
        ed192e92-84d4-4baf-997d-1e190a81f28e 36ee4c6c-0812-40a2-b820-b22ebd02bce3 MyNewApp
  summary: ""
- title: Retrieve an application by identifierUris
  code: |-
    Get-AzureADApplication -Filter "identifierUris/any(uri:uri eq 'http://wingtips.wingtiptoysonline.com')"
  description: ""
  summary: ""
parameters:
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: All
  description: |+
    If true, return all applications. If false, return the number of objects specified by the Top parameter

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Filter
  description: |+
    Specifies an oData v3.0 filter statement. This parameter controls which objects are returned.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ObjectId
  isRequired: true
  description: |+
    Specifies the ID of an application in Azure Active Directory.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: SearchString
  description: |+
    Specifies a search string.


  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: Top
  description: |+
    Specifies the maximum number of records to return.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: AzureADPreview.Get-AzureADApplication
name: Get-AzureADApplication
description: |-
  The **Get-AzureADApplication** cmdlet gets an Azure Active Directory application.
metadata:
  external help file: Microsoft.Open.AzureAD16.Graph.PowerShell.dll-Help.xml
  Module Name: AzureADPreview
  ms.assetid: FC0F8815-DEEC-4672-81A1-68A1095E5543
  ms.custom: iamfeature=PowerShell
  ms.reviewer: rodejo
  online version: ""
  schema: 2.0.0
