### YamlMime:PowershellCmdlet
summary: |-
  The Get-AzureADApplicationProxyApplication cmdlet retrieves an application configured for Application Proxy in Azure Active Directory.
module: AzureADPreview
notes: ""
inputs:
- name: <xref href="System.String" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="System.Object" data-throw-if-not-resolved="False" />
  description: ""
syntaxes:
- Get-AzureADApplicationProxyApplication -ObjectId <String> [<CommonParameters>]
examples:
- title: Example 1
  code: "PS C:\\> Get-AzureADApplicationProxyApplication -ObjectId 8d6c6684-6f8c-42e2-8914-32ed2adf9ccf\r\n\r\nExternalAuthenticationType               : AadPreAuthentication\r\nApplicationServerTimeout                 : Default\r\nExternalUrl                              : https://travel.cycles.adventure-works.com/\r\nInternalUrl                              : https://awcyclesapps.adventure-works.com:3000/\r\nIsTranslateHostHeaderEnabled             : False\r\nIsTranslateLinksInBodyEnabled            : False\r\nIsOnPremPublishingEnabled                : True\r\nVerifiedCustomDomainCertificatesMetadata : class OnPremisesPublishingVerifiedCustomDomainCertificatesMetadataObject {\r\n                                             Thumbprint:  [XXXXX]\r\n                                             SubjectName: [XXXXX]\r\n                                             Issuer: \r\n                                             IssueDate: 11/9/2017 5:54:29\r\n                                             ExpiryDate: 11/9/2019 5:54:29\r\n                                           }\r\n                                           \r\nVerifiedCustomDomainKeyCredential        : \r\nVerifiedCustomDomainPasswordCredential   : \r\nSingleSignOnSettings                     :"
  description: ""
  summary: ""
- title: Example 2
  code: |-
    foreach ($a in (Get-AzureADApplication -All:$true))
    {
        try
        {
            $p = Get-AzureADApplicationProxyApplication -ObjectId $a.ObjectId
            [pscustomobject]@{ObjectID=$a.ObjectId; DisplayName=$a.DisplayName; ExternalUrl=$p.ExternalUrl; InternalUrl=$p.InternalUrl}
        }
        catch
        {
            continue
        }
    }
  description: ""
  summary: |+
    Use the following script to get the list of Azure AD Application Proxy applications registered in your tenant:

parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ObjectId
  isRequired: true
  description: |+
    This is the unique application Id of the application. This can be found using the Get-AzureADApplication command. You can also find this in the Azure Portal by navigating to AAD, Enterprise Applications, All Applications, Select your application, go to the properties tab, and use the ObjectId on that page.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: AzureADPreview.Get-AzureADApplicationProxyApplication
name: Get-AzureADApplicationProxyApplication
description: |-
  The Get-AzureADApplicationProxyApplication cmdlet retrieves an application configured for Application Proxy in Azure Active Directory.
metadata:
  external help file: Microsoft.Open.MS.GraphBeta.PowerShell.dll-Help.xml
  Module Name: AzureADPreview
  online version: ""
  schema: 2.0.0
