### YamlMime:PowershellCmdlet
summary: |-
  Get detailed sign in summaries
module: AzureADPreview
notes: ""
outputs:
- name: <xref href="Microsoft.Online.Administration.GetApplicationSignInDetailedSummaryObjectsResponse" data-throw-if-not-resolved="False" />
  description: ""
syntaxes:
- Get-AzureADApplicationSignInDetailedSummary [-Top <Int32>] [-Filter <String>] [<CommonParameters>]
examples:
- title: 'Example 1: Get sign in detailed summary by application and date'
  code: |-
    PS C:\>Get-AzureADApplicationSignInDetailedSummary -Filter "appDisplayName eq 'Azure Portal' AND aggregatedEventDateTime gt 2019-05-01 AND aggregatedEventDateTime lt 2019-06-01"
  description: |-
    This command gets all sign ins to Azure Portal for the month of May.
  summary: ""
- title: 'Example 2: Get certain sign in failures'
  code: |-
    PS C:\>Get-AzureADApplicationSignInDetailedSummary -Filter "status/errorCode eq 0 50089"
  description: |-
    This command gets all sign ins that failed with 50089 code for "FailureReason: Flow token expired".
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Filter
  description: |+
    The oData v3.0 filter statement. 
    Controls which objects are returned.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: Top
  description: |+
    The maximum number of records to return.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: AzureADPreview.Get-AzureADApplicationSignInDetailedSummary
name: Get-AzureADApplicationSignInDetailedSummary
description: |-
  The Get-AzureADApplicationSignInDetailedSummary cmdlet gets Azure Active Directory sign ins, grouped by application, date, and sign in status.
metadata:
  external help file: Microsoft.Open.MS.GraphBeta.PowerShell.dll-Help.xml
  Module Name: AzureADPreview
  online version: ""
  schema: 2.0.0
