### YamlMime:PowershellCmdlet
summary: |-
  Retrieve the logo of an application
module: AzureADPreview
notes: ""
inputs:
- name: <xref href="System.String" data-throw-if-not-resolved="False" />
  description: |-
    System.Boolean
outputs:
- name: <xref href="System.Object" data-throw-if-not-resolved="False" />
  description: ""
syntaxes:
- >-
  Get-AzureADApplicationLogo -ObjectId <String> [-FilePath <String>] [-FileName <String>] [-View <Boolean>]

   [<CommonParameters>]
examples:
- title: Example 1
  code: |-
    PS C:\WINDOWS\system32> Get-AzureADApplicationLogo -ObjectId 79592454-dea7-4660-9d91-f1768e5055ac


    Tag                  :
    PhysicalDimension    : {Width=279, Height=390}
    Size                 : {Width=279, Height=390}
    Width                : 279
    Height               : 390
    HorizontalResolution : 96
    VerticalResolution   : 96
    Flags                : 77840
    RawFormat            : [ImageFormat: b96b3cae-0728-11d3-9d7b-0000f81ef32e]
    PixelFormat          : Format24bppRgb
    Palette              : System.Drawing.Imaging.ColorPalette
    FrameDimensionsList  : {7462dc86-6180-4c7e-8e3f-ee7333a7a483}
    PropertyIdList       : {274, 305, 306, 36867...}
    PropertyItems        : {274, 305, 306, 36867...}
  description: |-
    This example shows how to retrieve the application logo for an application that is specified through the Object ID parameter
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: FileName
  description: |+
    If provided, the application logo is copied to the file who's name is provided in this parameter 

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: FilePath
  description: |+
    If provided, the application logo is copied with a random filename to the file path that is specified in this parameter

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ObjectId
  isRequired: true
  description: |+
    The ObjectID of the application for which the logo is to be retrieved

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: View
  description: |+
    If set to $true, the application's logo is displayed in a new window on the screen.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: AzureADPreview.Get-AzureADApplicationLogo
name: Get-AzureADApplicationLogo
description: |-
  This cmdlet retrieves the logo that is set for an application.
metadata:
  external help file: Microsoft.Open.AzureAD16.Graph.PowerShell.Custom.dll-Help.xml
  Module Name: AzureADPreview
  ms.custom: iamfeature=PowerShell
  ms.reviewer: stevemutungi
  online version: ""
  schema: 2.0.0
