### YamlMime:PowershellCmdlet
summary: |-
  Gets the owner of an application.
module: AzureADPreview
notes: ""
links:
- text: Add-AzureADApplicationOwner
  href: ./Add-AzureADApplicationOwner.yml
- text: Remove-AzureADApplicationOwner
  href: ./Remove-AzureADApplicationOwner.yml
syntaxes:
- Get-AzureADApplicationOwner -ObjectId <String> [-All <Boolean>] [-Top <Int32>] [<CommonParameters>]
examples:
- title: 'Example 1: Get the owner of an application'
  code: |-
    PS C:\>Get-AzureADApplicationOwner -ObjectId "aaaaaaaa-0000-1111-2222-bbbbbbbbbbbb"

    ObjectId                             ObjectType
    --------                             ----------
    c13dd34a-492b-4561-b171-40fcce2916c5 User
  description: |-
    This command gets the owner of an application.
  summary: ""
parameters:
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: All
  description: |+
    If true, return all owners. If false, return the number of objects specified by the Top parameter

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ObjectId
  isRequired: true
  description: |+
    Specifies the ID of an application in Azure Active Directory.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: Top
  description: |+
    Specifies the maximum number of records to return.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: AzureADPreview.Get-AzureADApplicationOwner
name: Get-AzureADApplicationOwner
description: |-
  The **Get-AzureADApplicationOwner** cmdlet get an owner of an Azure Active Directory application.
metadata:
  external help file: Microsoft.Open.AzureAD16.Graph.PowerShell.dll-Help.xml
  Module Name: AzureADPreview
  ms.assetid: 45C6B663-1AD4-4ED3-81BB-D2B79C67BC47
  ms.custom: iamfeature=PowerShell
  ms.reviewer: rodejo
  online version: ""
  schema: 2.0.0
