### YamlMime:PowershellCmdlet
summary: |-
  Creates a password credential for an application.
module: AzureADPreview
notes: ""
links:
- text: Get-AzureADApplicationPasswordCredential
  href: ./Get-AzureADApplicationPasswordCredential.yml
- text: Remove-AzureADApplicationPasswordCredential
  href: ./Remove-AzureADApplicationPasswordCredential.yml
syntaxes:
- >-
  New-AzureADApplicationPasswordCredential -ObjectId <String> [-CustomKeyIdentifier <String>]

   [-StartDate <DateTime>] [-EndDate <DateTime>] [-Value <String>] [-InformationAction <ActionPreference>]

   [-InformationVariable <String>] [<CommonParameters>]
examples:
- title: 'Example 1: Create a password credential'
  code: |-
    PS C:\>New-AzureADApplicationPasswordCredential -ObjectId "3ddd22e7-a150-4bb3-b100-e410dea1cb84"

    CustomKeyIdentifier :
    EndDate             : 9/28/2017 3:57:10 PM
    KeyId               :
    StartDate           : 9/28/2016 3:57:10 PM
    Value               : ZJ0V1Yg4cp4eWIey9DrYspqVdX1pdvY437P/ueGxVLU=
  description: ""
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: CustomKeyIdentifier
  description: ""
  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="DateTime" data-throw-if-not-resolved="False" />
  name: EndDate
  description: ""
  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="ActionPreference" data-throw-if-not-resolved="False" />
  name: InformationAction
  description: |+
    Specifies how this cmdlet responds to an information event. The acceptable values for this parameter are:

    - Continue
    - Ignore
    - Inquire
    - SilentlyContinue
    - Stop
    - Suspend

  defaultValue: None
  position: Named
  aliases: infa
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: InformationVariable
  description: |+
    Specifies an information variable.

  defaultValue: None
  position: Named
  aliases: iv
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ObjectId
  isRequired: true
  description: |+
    Specifies the ID of a user in Azure AD.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="DateTime" data-throw-if-not-resolved="False" />
  name: StartDate
  description: ""
  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Value
  description: ""
  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: AzureADPreview.New-AzureADApplicationPasswordCredential
name: New-AzureADApplicationPasswordCredential
description: |-
  The **New-AzureADApplicationPasswordCredential** cmdlet creates a password credential for an application in Azure Active Directory (AD).
metadata:
  external help file: Microsoft.Open.AzureAD16.Graph.PowerShell.Custom.dll-Help.xml
  Module Name: AzureADPreview
  ms.assetid: D3B591A4-A99D-4D2D-90E2-D4CE016C4589
  ms.custom: iamfeature=PowerShell
  ms.reviewer: stevemutungi
  online version: ""
  schema: 2.0.0
