### YamlMime:PowershellCmdlet
summary: |-
  Removes an application policy.
module: AzureADPreview
notes: ""
syntaxes:
- >-
  Remove-AzureADApplicationPolicy -Id <String> -PolicyId <String> [-InformationAction <ActionPreference>]

   [-InformationVariable <String>] [<CommonParameters>]
examples:
- title: 'Example 1: Remove an application policy'
  code: |-
    PS C:\>Remove-AzureADApplicationPolicy -ObjectId <object id of application> -PolicyId <object id of policy>
  description: |-
    This command removes the specified application policy.
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Id
  isRequired: true
  description: |+
    {{Fill Id Description}}

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="ActionPreference" data-throw-if-not-resolved="False" />
  name: InformationAction
  description: |+
    Specifies how this cmdlet responds to an information event.
    The acceptable values for this parameter are:

    - Continue
    - Ignore
    - Inquire
    - SilentlyContinue
    - Stop
    - Suspend

  defaultValue: None
  position: Named
  aliases: infa
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: InformationVariable
  description: |+
    Specifies an information variable.

  defaultValue: None
  position: Named
  aliases: iv
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: PolicyId
  isRequired: true
  description: |+
    Specifies the ID of the policy.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: AzureADPreview.Remove-AzureADApplicationPolicy
name: Remove-AzureADApplicationPolicy
description: |-
  The Remove-AzureADApplicationPolicy cmdlet removes an application policy from Azure Active Directory (AD).
metadata:
  external help file: Microsoft.Open.MS.GraphBeta.PowerShell.dll-Help.xml
  Module Name: AzureADPreview
  online version: ""
  schema: 2.0.0
