### YamlMime:PowershellCmdlet
summary: |-
  Removes an owner from an application.
module: AzureADPreview
notes: ""
links:
- text: Add-AzureADApplicationOwner
  href: ./Add-AzureADApplicationOwner.yml
- text: Get-AzureADApplicationOwner
  href: ./Get-AzureADApplicationOwner.yml
syntaxes:
- >-
  Remove-AzureADApplicationOwner -ObjectId <String> -OwnerId <String> [-InformationAction <ActionPreference>]

   [-InformationVariable <String>] [<CommonParameters>]
examples:
- title: 'Example 1: Remove an owner from an application'
  code: |-
    PS C:\>Remove-AzureADApplicationOwner -ObjectId "3ddd22e7-a150-4bb3-b100-e410dea1cb84" -OwnerId "c13dd34a-492b-4561-b171-40fcce2916c5"
  description: |-
    This command removes the owner from the specified application.
  summary: ""
parameters:
- type: <xref href="ActionPreference" data-throw-if-not-resolved="False" />
  name: InformationAction
  description: |+
    Specifies how this cmdlet responds to an information event.

    The acceptable values for this parameter are:

    - Continue
    - Ignore
    - Inquire
    - SilentlyContinue
    - Stop
    - Suspend

  defaultValue: None
  position: Named
  aliases: infa
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: InformationVariable
  description: |+
    Specifies an information variable.

  defaultValue: None
  position: Named
  aliases: iv
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ObjectId
  isRequired: true
  description: |+
    Specifies the ID of an application in Azure AD.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: OwnerId
  isRequired: true
  description: |+
    Specifies the ID of the owner.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: AzureADPreview.Remove-AzureADApplicationOwner
name: Remove-AzureADApplicationOwner
description: |-
  The **Remove-AzureADApplicationOwner** cmdlet removes an owner from an application in Azure Active Directory (AD).
metadata:
  external help file: Microsoft.Open.AzureAD16.Graph.PowerShell.dll-Help.xml
  Module Name: AzureADPreview
  ms.assetid: 6B318FF5-2DD5-485A-A4BA-C2E9F7CA1DEC
  ms.custom: iamfeature=PowerShell
  ms.reviewer: stevemutungi
  online version: ""
  schema: 2.0.0
