### YamlMime:PowershellCmdlet
summary: |-
  Deletes an extension property from an application object.
module: AzureADPreview
notes: ""
inputs:
- name: <xref href="string" data-throw-if-not-resolved="False" />
  description: ""
syntaxes:
- >-
  Remove-AzureADMSApplicationExtensionProperty -ObjectId <String> -ExtensionPropertyId <String>

   [<CommonParameters>]
examples:
- title: 'Example 1: Remove an extension property'
  code: |-
    PS C:\> Remove-AzureADMSApplicationExtensionProperty -ObjectId "aaaaaaaa-0000-1111-2222-bbbbbbbbbbbb" -ExtensionPropertyId "344ed560-f8e7-410e-ab9f-c79df5c36"
  description: |-
    This command removes the extension property that has the specified ID from an application in Azure Active Directory.
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ExtensionPropertyId
  isRequired: true
  description: |+
    Specifies the unique ID of the extension property to remove.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ObjectId
  isRequired: true
  description: |+
    Specifies the unique ID of an application in Azure Active Directory.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: AzureADPreview.Remove-AzureADMSApplicationExtensionProperty
name: Remove-AzureADMSApplicationExtensionProperty
description: |-
  Deletes an extension property from an application object.
metadata:
  external help file: Microsoft.Open.MS.GraphBeta.PowerShell.dll-Help.xml
  Module Name: AzureADPreview
  online version: ""
  schema: 2.0.0
